// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaf0CADtFtCQJH-QeotjEgBACQKGFhob4',
    appId: '1:132953159289:web:0f32063b14d8119a0e06a8',
    messagingSenderId: '132953159289',
    projectId: 'zomatunes-739e2',
    authDomain: 'zomatunes-739e2.firebaseapp.com',
    databaseURL: 'https://zomatunes-739e2-default-rtdb.firebaseio.com',
    storageBucket: 'zomatunes-739e2.appspot.com',
    measurementId: 'G-1854WYWXHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO1kQWApTokR6iF4GGumuSjP3Ufd0S4bg',
    appId: '1:132953159289:android:c5c72cd4ee5a4d600e06a8',
    messagingSenderId: '132953159289',
    projectId: 'zomatunes-739e2',
    databaseURL: 'https://zomatunes-739e2-default-rtdb.firebaseio.com',
    storageBucket: 'zomatunes-739e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_0VlSK0scVJ6YmHKAzpmf1POmH-1BD4Q',
    appId: '1:132953159289:ios:68d0d1ab7ef288c80e06a8',
    messagingSenderId: '132953159289',
    projectId: 'zomatunes-739e2',
    databaseURL: 'https://zomatunes-739e2-default-rtdb.firebaseio.com',
    storageBucket: 'zomatunes-739e2.appspot.com',
    androidClientId: '132953159289-ab3os4pnvv9btbl2gahcfp6nlb3iuh0o.apps.googleusercontent.com',
    iosClientId: '132953159289-tihjn4c5hptnftpt3fopotnhlro0vtj8.apps.googleusercontent.com',
    iosBundleId: 'com.savvy.komkum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_0VlSK0scVJ6YmHKAzpmf1POmH-1BD4Q',
    appId: '1:132953159289:ios:68d0d1ab7ef288c80e06a8',
    messagingSenderId: '132953159289',
    projectId: 'zomatunes-739e2',
    databaseURL: 'https://zomatunes-739e2-default-rtdb.firebaseio.com',
    storageBucket: 'zomatunes-739e2.appspot.com',
    androidClientId: '132953159289-ab3os4pnvv9btbl2gahcfp6nlb3iuh0o.apps.googleusercontent.com',
    iosClientId: '132953159289-tihjn4c5hptnftpt3fopotnhlro0vtj8.apps.googleusercontent.com',
    iosBundleId: 'com.savvy.komkum',
  );
}
